AGROCAPITAL_PRODUCTS = {
    "credito_refaccionario": {
        "name": "Credito Refaccionario",
        "use_cases": [
            "maquinaria",
            "terreno",
            "terrenos agricolas",
            "infraestructura",
            "equipamiento",
            "riego",
            "sistemas de riego",
        ],
        "summary": "Adquisicion de maquinaria, terrenos agricolas, infraestructura y equipamiento.",
        "term": "Hasta 15 anos.",
        "fees": "Comision por apertura 1.5% y comision FEGA 1.26%.",
        "cat": "CAT promedio 18.5% sin IVA, fecha de calculo 02 de agosto 2022.",
        "source": "Agrocapital",
        "source_url": "https://agrocapital.com.mx/productos-y-servicios.html",
    },
    "capital_trabajo": {
        "name": "Capital de Trabajo",
        "use_cases": [
            "flujo",
            "flujo efectivo",
            "operacion",
            "mantenimiento",
            "administracion",
            "capital de trabajo",
        ],
        "summary": "Requerimientos de flujo efectivo para proyectos agricolas, industriales, ganaderos y de pesca.",
        "term": "Hasta 1 ano y renovable.",
        "fees": "Comision por apertura 1.5% y comision FEGA 1.26%.",
        "cat": "CAT promedio 21.0% sin IVA, fecha de calculo 02 de agosto 2022.",
        "source": "Agrocapital",
        "source_url": "https://agrocapital.com.mx/productos-y-servicios.html",
    },
    "credito_avio": {
        "name": "Credito de Habilitacion o Avio",
        "use_cases": [
            "insumos",
            "siembra",
            "ciclo agricola",
            "cultivo",
            "maiz",
            "frijol",
            "trigo",
            "papa",
            "sorgo",
            "garbanzo",
            "frutales",
            "jornales",
        ],
        "summary": "Financiamiento para cultivos y ciclo productivo.",
        "term": "Ciclo productivo del cultivo.",
        "fees": "Comision por apertura 1.5% y comision FEGA 1.26%.",
        "cat": "CAT promedio 24.3% sin IVA, fecha de calculo 02 de agosto 2022.",
        "source": "Agrocapital",
        "source_url": "https://agrocapital.com.mx/productos-y-servicios.html",
    },
    "arrendamiento_puro": {
        "name": "Arrendamiento Puro",
        "use_cases": [
            "vehiculo",
            "vehiculos",
            "parque vehicular",
            "reposicion vehicular",
            "arrendamiento",
        ],
        "summary": "Adquisicion o reposicion de parque vehicular.",
        "term": "3 anos.",
        "fees": None,
        "cat": None,
        "source": "Agrocapital",
        "source_url": "https://agrocapital.com.mx/productos-y-servicios.html",
    },
    "financiamiento_rural": {
        "name": "Financiamiento Rural",
        "use_cases": [
            "actividad rural",
            "medio rural",
            "negocio rural",
            "comercio rural",
        ],
        "summary": "Financiamiento para actividad economica en medio rural.",
        "term": "Sujeto a analisis.",
        "fees": None,
        "cat": None,
        "source": "Agrocapital",
        "source_url": "https://agrocapital.com.mx/productos-y-servicios.html",
    },
    "credito_empresarial": {
        "name": "Credito Empresarial",
        "use_cases": [
            "empresa",
            "agroindustria",
            "agroindustrial",
            "desarrollo empresarial",
            "fortalecimiento empresarial",
        ],
        "summary": "Creacion, desarrollo y fortalecimiento de empresas del sector agroindustrial.",
        "term": "Sujeto a analisis.",
        "fees": None,
        "cat": None,
        "source": "Agrocapital",
        "source_url": "https://agrocapital.com.mx/productos-y-servicios.html",
    },
    "credito_prendario": {
        "name": "Credito Prendario",
        "use_cases": [
            "inventario",
            "inventarios",
            "comercializacion",
            "cosecha",
            "cosechas",
            "granos",
            "semillas",
            "fertilizantes",
            "garantia prendaria",
        ],
        "summary": "Comercializacion de cosechas e inventarios usando los mismos inventarios como garantia.",
        "term": "Hasta 180 dias.",
        "fees": "Comision por apertura 1.5% y comision FEGA 1.26%.",
        "cat": "CAT promedio 18.8% sin IVA, fecha de calculo 02 de agosto 2022.",
        "source": "Agrocapital",
        "source_url": "https://agrocapital.com.mx/productos-y-servicios.html",
    },
}

AGROCAPITAL_SERVICES = [
    "Financiamiento puro",
    "Administracion de credito",
    "Asesoria tecnica especializada",
    "Tasas de interes preferenciales",
    "Seguro agricola",
    "Integracion de la cadena productiva",
    "Administracion de coberturas de precios",
    "Solucion a la comercializacion de cosechas",
    "Respaldo de empresas con vocacion agropecuaria",
    "Innovacion y tecnologia para el campo",
]

REQUIRED_DOCUMENTS = [
    "identificacion",
    "comprobante fiscal",
    "comprobante domicilio",
    "cotizacion",
    "documentos del predio",
    "estados financieros",
]
